### ISSUE TITLE
Need some examples of action function

### ISSUE THREAD

**Issue by CurlyBraceTT** [cskeppstedt/json-post-process-webpack-plugin#3]
Everything gives me an error "Unexpected identifier". I quess I just missed something on how this works.
Simple coniguration, which fails:

```
plugins: [
        new JsonPostProcessPlugin({
            matchers: [{
                matcher: /^test.json$/,
                action: (currentJsonContent) => ({ return currentJsonContent; })
            }]
        })
]
```

**Comment by CurlyBraceTT** [comment]
nvm, action should be:

`action: (currentJsonContent) => { return currentJsonContent; }`

**Comment by cskeppstedt** [comment]
Yes those parenthesis would turn the body of the `action` function to be something that returns an object, with the content of the object being `return ..` which is invalid syntax of course :) 👍
